name: Deploy SCP

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 

  scp-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::695327934036:role/OIDCRoleForGitHub
          role-session-name: samplerolesession

      - name: Deploy SCP
        run: |
          aws organizations create-policy --content file://EshwarTestSCP.json --description "My SCP" --name MySCP --type SERVICE_CONTROL_POLICY

  