name: Deploy SCP

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 

  scp-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::695327934036:role/OIDCRoleForGitHub
          role-session-name: samplerolesession

      - name: deploy SCP
        run: |
          python scp.py
      

  