name: Deploy SCP

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 

  scp-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::695327934036:role/EshwarGithubRole
          role-session-name: samplerolesession

      - name: Deploy SCP
        run: |
    
          config=$(jq -r '.SCPs[]' configuration.json)

          echo "$config" | while read scp; do
            policy_id=$(aws organizations create-policy --content file://$(echo $scp | jq -r '.path') --description "My SCP" --name $(echo $scp | jq -r '.name') --type SERVICE_CONTROL_POLICY --query 'Policy.PolicySummary.Id' --output text)
            aws organizations attach-policy --policy-id ${policy_id} --target-id $(echo $scp | jq -r '.targetOU')
          done
  