name: Deploy SCP

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 

  scp-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::695327934036:role/EshwarGithubRole
          role-session-name: samplerolesession

      - name: Deploy SCP
        run: |
          root_id=$(aws organizations list-roots --query 'Roots[0].Id' --output text)

          jq -c '.SCPs[]' configuration.json | while IFS= read -r scp; do
            scp_path=$(echo $scp | jq -r '.path')
            scp_name=$(echo $scp | jq -r '.name')
        
            policy_id=$(aws organizations list-policies --filter SERVICE_CONTROL_POLICY --query 'Policies[?Name==`'${scp_name}'`].Id' --output text)
        
            if [ -n "$policy_id" ]; then
              aws organizations list-targets-for-policy --policy-id ${policy_id} --query 'Targets[].TargetId' --output text | while read -r target_id; do
                aws organizations detach-policy --policy-id ${policy_id} --target-id ${target_id}
              done
              aws organizations delete-policy --policy-id ${policy_id}
            fi
        
            policy_id=$(aws organizations create-policy --content file://${scp_path} --description "My SCP" --name ${scp_name} --type SERVICE_CONTROL_POLICY --query 'Policy.PolicySummary.Id' --output text)
        
            aws organizations attach-policy --policy-id ${policy_id} --target-id ${root_id}
          done