name: Deploy base VPC cloudformation stack

on: 
  workflow_dispatch:

jobs: 
  cfn-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: deploy VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: git-stack-vpc
          template: vpc.yml
      

  