name: Deploy base VPC cloudformation stack

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 

  cfn-deployment: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code from main branch
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::024111598068:role/githubactions-cfn
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-east-2 # use your region here.

      - name: deploy VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: git-stack-vpc
          template: vpc.yml
      

  